Feature/tab component
EEBOS/owl-ui pull request #47
Opened 2022-05-26 17:20 UTC by ValerieOseiOSG

### Short summary

Isolated tab component for single PR review

2022-05-26 17:42 UTC, CiceroFonsecaOSG commented
[sc-852]

2022-05-26 19:01 UTC, CiceroFonsecaOSG requested changes

2022-05-26 19:01 UTC, CiceroFonsecaOSG commented on packages/tabs/src/TabButton/TabButton.tsx
> +import * as React from 'react';
as discussed on Slack, we need to use the `yarn create:component -o` script to create component options (sub-components).

What you could do is check out the `CardHeader` component `packages/card/src/CardHeader` and update your files according to this template, but returning the proper markup for the button, content, item, and wrapper.

2022-06-09 13:45 UTC, closed without merging

2022-06-09 13:46 UTC, ValerieOseiOSG commented
Closing this PR, as it related to sc-852 which has been archived -  a new story addressing the refactor of the tabs component has been created.